# generated by datamodel-codegen:
#   filename:  o2-product-set.json
#   timestamp: 2025-06-11T17:38:18+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, field_validator


class Handset(BaseModel):
    brand: str
    name: str
    code: str
    averageRating: float
    totalReviews: int
    inStock: bool
    isFiveGReady: bool
    isSwitchUpEligible: bool
    skuCode: str

class HandsetColour(BaseModel):
    name: str
    hexCode: str

    @field_validator("hexCode", mode="before")
    @classmethod
    def validate_hex_color(cls, v):
        import re

        if not re.fullmatch(r"#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})", v):
            raise ValueError("Invalid hex color code")
        return v


class Tariff(BaseModel):
    planOfferingCode: str
    name: str
    totalUpfront: int
    airtimeMrc: float
    deviceMrc: float
    api: float
    contractDuration: int
    tariffExtras: list[Extras]


class Extras(BaseModel):
    name: str
    code: str

    def __hash__(self):
        return hash((self.code,))
